### ISSUE TITLE
add and configure by default sonarqube instance and scanner.

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#11]
default sonar token should be used for integration.
By default PR checker should be configured correctly right after install for free version of the Jenkins instance

**Comment by vdelendik** [comment]
default Sonar instance in qps-infra should be configured for:

PR checker in carina-demo project
unit tests coverage for carina-demo
integration code coverage calculation for carina-demo

**Comment by vdelendik** [comment]
jenkins-master: 5.0-beta4 
@okamara, ask @sandinosanchez about test scenario.

Changes in the code: https://github.com/qaprosoft/jenkins-master/pull/200

**Comment by sandinosanchez** [comment]
Test scenario:
 Pre conditions:
   1. demo server configured with QPS_PIPELINE_GIT_BRANCH=develop
   2. organization & repository jobs executed
   3. ghprbhook-token configured

Steps:
   1. Open http://demo.qaprosoft.com/jenkins and login
   2. Create/re-open pull request in correspondant github repository

Expected results:
   2. 
       - onPullRequestJobTrigger, onPullRequestJob executed
       - onPullRequestJob build state = SUCCESS
       - link to the sonar ui report shown in onPullRequestJob console

<img width="809" alt="Run sensors on project" src="https://user-images.githubusercontent.com/43247306/80372484-fa452300-8869-11ea-8e1c-841d486c1c66.png">

**Comment by okamara** [comment]
It doesn't work for me.
I see errors in console log for Pull request job:
[INFO] [jenkins-event-spy] Generated /var/jenkins_home/jobs/okamara/jobs/carina-demo/jobs/onPullRequest-carina-demo/workspace@tmp/withMavenf2cc6b4d/maven-spy-20200427-144606-7433731657711444018875.log
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project carina-demo: Not authorized. Please check the properties sonar.login and sonar.password. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
[withMaven] Publishers:

**Comment by okamara** [comment]
I still can't see that Pull request executed Pull Request jobs.

**Comment by sandinosanchez** [comment]
**Disclaimer**: starting from sonarqube 6.x unit and integration test coverage have been merged into a single representation. See the following [link](https://community.sonarsource.com/t/making-test-coverage-measures-mode-useful/291) for more info. Moreover in order to enable integration coverage a valid aws jacoco credential is required, otherwise only unit test coverage is presented.

changes could be seeing in [qps-pipeline#735](https://github.com/qaprosoft/qps-pipeline/pull/735), #221 

Pre conditions: 
 - your infra instance configured with QPS_PIPELINE_GIT_BRANCH=develop.
 - organization job executed.
 - ghprbhook-token configured.
 - sonarqube token created in jenkins (see [qps-infra#164](https://github.com/qaprosoft/qps-infra/issues/164) for more info).
 - .sonarqube file created in the organization repository (see [qps-infra#167](https://github.com/qaprosoft/qps-infra/issues/167) for more info).
 - jacoco aws token configured in jenkins credentials.
 - GITHUB_OATH_TOKEN with write permission added into jenkins global variables.

Test case:
  1. Run RegisterRepository with carina-demo
  2. Create a branch from master and add
       `private String unUsedVar;` into src/main/java/com/qaprosoft/carina/demo/gui/pages/HomePage.java
  3. Create a pull request.

Expected Results: 
1.  - onPushJob executed successfully, link to the sonar analysis report returned in the console output.
     - Click the link and unit test coverage, issues, blockers shown in the sonar ui.
 
3. - onPullRequestJobTrigger and onPullRequestJob triggered.
    - Comment added into the pr automatically from the user with permission pointing out sonarqube issues.

**Comment by okamara** [comment]
Tested on local env. done
